# SITE CONFIGURATION
title: QuarkenDyk
author: QuarkenDyk
description: > # Meta description of Homepage
  Dykutbildning, dykutrustning, service av dykutrustning
baseurl: ""
url: "https://quarkendyk.se"

# SEO PLUGIN
social:
  name: QuarkenDyk
  links:
    - https://www.facebook.com/quarkendyk/
    - https://www.instagram.com/quarkendyk/

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Hem', link: '/'}
  - {name: 'Försäljning', link: '/utrustning'}
  - {name: 'Kursutbud', link: '/kursutbud'}
  - {name: 'Service', link: '/service'}


  # - {name: 'Contact', link: '/contact'}

tagline: >
  Dykutbildning - Dykutrustning - Utrustningsservice

hero_img: banner.JPG # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: info@quarkendyk.se # email for form submission

facebook_username:  quarkendyk # replace with your_github_username or comment to remove link from footer
instagram_username: quarkendyk # replace with your_instagram_username or comment to remove link from footer

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  kurser:
    output: true
