lang: se
title: Umeådyksällskap
copyright: © 2024. All rights reserved.

accent_image: /assets/img/sidebar-bg.jpg
accent_color: rgb(79,177,186)
theme_color: rgb(25,55,71)

logo: /assets/img/logo.png

font: Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif
google_fonts: false

menu:
  - title: Bli medlem
    url: /medlemskap
  - title: Dykplatser
    url: /dykplatser/
  # - title: Service
  #   url: /service/
  - title: Utbildning
    url: /utbildning/
  - title: Blog
    url: /blog

hydejack:
  post_addons: [about, newsletter, related, random, comments]
  project_addons: [about, newsletter, other, comments]

  no_mark_external: false
  no_push_state: false
  no_drawer: true
  no_navbar: true
  no_search: true
  no_inline_css: true
  no_page_style: false
  no_break_layout: true
  no_toc: false
  no_third_column: false
  no_large_headings: false
  no_structured_data: false
  no_theme_color: false
  no_breadcrumbs: false

  use_lsi: true
  cookies_banner: false
  advertise: true
  hide_dates: false
  hide_last_modified: false

  dark_mode:
    always: false
    dynamic: false
    sunrise: 6
    sunset: 18
    icon: true

  offline:
    enabled: false
    cache_version: 1
    precache_assets:
      - /assets/img/swipe.svg

optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true
  with_frontmatter: true

relative_links:
  collections: true

titles_from_headings:
  strip_title: true
  collections: true

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all
  ignore:
    envs: [development]

sass:
  style: compressed

disable_disk_cache: true
baseurl: "/"
